name: End-to-end tests

on: [push]

env:
  APP_STATE: "testing"
  TESTING: True
  DEBUG: True

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Create .env file
      run: |
        touch .env
        echo APP_STATE="testing" > .env
        echo SECRET_KEY="justtesting" > .env
        echo DB_STRING="sqlite://" > .env
        cat .env

    - name: Run flask testing server
      run: |
        nohup pipenv run flask run 2>&1 &
      env:
          APP_STATE: "testing"
          SECRET_KEY: "justtesting"
          DB_STRING: "sqlite://"

    - name: Run cypress tests
      # uses: cypress-io/github-action@v2
      run: |
        cd cypress
        npm install
        npm run test

