name: Integration tests

on: [push]

env:
  APP_STATE: "testing"
  TEST_DB_STRING: "sqlite:///database.db"
  SECRET_KEY: "randomsecretkey"
  FLASK_APP: "kucharka"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --dev
        poetry run playwright install

    - name: Test with playwright
      run: |
        poetry run pytest -c pyproject.toml -m "integration"
