name: Integration tests

on: [push]

env:
  APP_STATE: "testing"
  TEST_DB_STRING: "sqlite://"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # - name: cache pipenv
    #   id: cache-pipenv
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    - name: Install dependencies
      # if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        pipenv run playwright install

    - name: Test with pytest
      run: |
        pipenv run pytest -c pyproject.toml -m "integration"

  
