name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Test with pytest
      env:
          APP_STATE: "testing"

          TESTING_SECRET_KEY: "justtesting"
          TESTING_DB_STRING: "sqlite://"

          SECRET_KEY: "justtesting"
          SQLALCHEMY_DATABASE_URI: "sqlite://"
          
          SENTRY_MONITORING: False
          STORAGE_SYSTEM: "LOCAL"

      run: |
        pipenv run pytest

    - name: Start server
      env:
          APP_STATE: "development"
      run: |
        pipenv run flask run

    - name: Run cypress tests
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        wait-on: 'http://localhost:5000'


